const POPULAR_STOCKS = [
  { symbol: '005930', name: '삼성전자', exchange: 'KOSPI' },
  { symbol: '000660', name: 'SK하이닉스', exchange: 'KOSPI' },
  { symbol: '035420', name: 'NAVER', exchange: 'KOSPI' },
  { symbol: '035720', name: '카카오', exchange: 'KOSPI' },
  { symbol: '005380', name: '현대차', exchange: 'KOSPI' },
  { symbol: '000270', name: '기아', exchange: 'KOSPI' },
  { symbol: '068270', name: '셀트리온', exchange: 'KOSPI' },
  { symbol: '051910', name: 'LG화학', exchange: 'KOSPI' },
  { symbol: '006400', name: '삼성SDI', exchange: 'KOSPI' },
  { symbol: '105560', name: 'KB금융', exchange: 'KOSPI' },
  { symbol: '055550', name: '신한지주', exchange: 'KOSPI' },
  { symbol: '003550', name: 'LG', exchange: 'KOSPI' },
  { symbol: '017670', name: 'SK텔레콤', exchange: 'KOSPI' },
  { symbol: '030200', name: 'KT', exchange: 'KOSPI' },
  { symbol: '032830', name: '삼성생명', exchange: 'KOSPI' },
  { symbol: '028260', name: '삼성물산', exchange: 'KOSPI' },
  { symbol: '012330', name: '현대모비스', exchange: 'KOSPI' },
  { symbol: '066570', name: 'LG전자', exchange: 'KOSPI' },
  { symbol: '009150', name: '삼성전기', exchange: 'KOSPI' },
  { symbol: '034730', name: 'SK', exchange: 'KOSPI' },
  { symbol: '015760', name: '한국전력', exchange: 'KOSPI' },
  { symbol: '086790', name: '하나금융지주', exchange: 'KOSPI' },
  { symbol: '018260', name: '삼성에스디에스', exchange: 'KOSPI' },
  { symbol: '011070', name: 'LG이노텍', exchange: 'KOSPI' },
  { symbol: '207940', name: '삼성바이오로직스', exchange: 'KOSPI' },
  { symbol: '003490', name: '대한항공', exchange: 'KOSPI' },
  { symbol: '042700', name: '한미반도체', exchange: 'KOSPI' },
  { symbol: '373220', name: 'LG에너지솔루션', exchange: 'KOSPI' },
  { symbol: '000810', name: '삼성화재', exchange: 'KOSPI' },
  { symbol: '032640', name: 'LG유플러스', exchange: 'KOSPI' },
  { symbol: '259960', name: '크래프톤', exchange: 'KOSPI' },
  { symbol: '352820', name: '하이브', exchange: 'KOSPI' },
  { symbol: '247540', name: '에코프로비엠', exchange: 'KOSDAQ' },
  { symbol: '086520', name: '에코프로', exchange: 'KOSDAQ' },
  { symbol: '196170', name: '알테오젠', exchange: 'KOSDAQ' },
  { symbol: '293490', name: '카카오게임즈', exchange: 'KOSDAQ' },
  { symbol: '263750', name: '펄어비스', exchange: 'KOSDAQ' },
  { symbol: '041510', name: 'SM엔터테인먼트', exchange: 'KOSDAQ' },
  { symbol: '035900', name: 'JYP엔터테인먼트', exchange: 'KOSDAQ' },
  { symbol: '122870', name: '와이지엔터테인먼트', exchange: 'KOSDAQ' },
  { symbol: '091990', name: '셀트리온헬스케어', exchange: 'KOSDAQ' },
  { symbol: '145020', name: '휴젤', exchange: 'KOSDAQ' },
  { symbol: '214150', name: '클래시스', exchange: 'KOSDAQ' },
  { symbol: '096770', name: 'SK이노베이션', exchange: 'KOSPI' },
  { symbol: '011200', name: 'HMM', exchange: 'KOSPI' },
  { symbol: '316140', name: '우리금융지주', exchange: 'KOSPI' },
  { symbol: '138040', name: '메리츠금융지주', exchange: 'KOSPI' },
  { symbol: '024110', name: '기업은행', exchange: 'KOSPI' },
  { symbol: '251270', name: '넷마블', exchange: 'KOSPI' },
  { symbol: '112040', name: '위메이드', exchange: 'KOSDAQ' },
  { symbol: '067160', name: '아프리카TV', exchange: 'KOSDAQ' },
  // 추가
  { symbol: '012450', name: '한화에어로스페이스', exchange: 'KOSPI' },
  { symbol: '329180', name: 'HD현대중공업', exchange: 'KOSPI' },
  { symbol: '267250', name: 'HD현대', exchange: 'KOSPI' },
  { symbol: '009540', name: 'HD한국조선해양', exchange: 'KOSPI' },
  { symbol: '042660', name: '한화오션', exchange: 'KOSPI' },
  { symbol: '010620', name: 'HD현대미포', exchange: 'KOSPI' },
  { symbol: '010140', name: '삼성중공업', exchange: 'KOSPI' },
  { symbol: '047810', name: '한국항공우주', exchange: 'KOSPI' },
  { symbol: '272210', name: '한화시스템', exchange: 'KOSPI' },
  { symbol: '079550', name: 'LIG넥스원', exchange: 'KOSPI' },

  { symbol: '010120', name: 'LS ELECTRIC', exchange: 'KOSPI' },
  { symbol: '267260', name: 'HD현대일렉트릭', exchange: 'KOSPI' },
  { symbol: '001440', name: '대한전선', exchange: 'KOSPI' },
  { symbol: '006260', name: 'LS', exchange: 'KOSPI' },
  { symbol: '000720', name: '현대건설', exchange: 'KOSPI' },
  { symbol: '028050', name: '삼성E&A', exchange: 'KOSPI' },
  { symbol: '336260', name: '두산퓨얼셀', exchange: 'KOSPI' },
  { symbol: '034020', name: '두산에너빌리티', exchange: 'KOSPI' },
  { symbol: '271560', name: '오리온', exchange: 'KOSPI' },
  { symbol: '097950', name: 'CJ제일제당', exchange: 'KOSPI' },

  { symbol: '000100', name: '유한양행', exchange: 'KOSPI' },
  { symbol: '128940', name: '한미약품', exchange: 'KOSPI' },
  { symbol: '006280', name: '녹십자', exchange: 'KOSPI' },
  { symbol: '326030', name: 'SK바이오팜', exchange: 'KOSPI' },
  { symbol: '302440', name: 'SK바이오사이언스', exchange: 'KOSPI' },
  { symbol: '336370', name: '솔루스첨단소재', exchange: 'KOSPI' },
  { symbol: '003670', name: '포스코퓨처엠', exchange: 'KOSPI' },
  { symbol: '066970', name: '엘앤에프', exchange: 'KOSDAQ' },
  { symbol: '278280', name: '천보', exchange: 'KOSDAQ' },
  { symbol: '348370', name: '엔켐', exchange: 'KOSDAQ' },

  { symbol: '357780', name: '솔브레인', exchange: 'KOSDAQ' },
  { symbol: '240810', name: '원익IPS', exchange: 'KOSDAQ' },
  { symbol: '058470', name: '리노공업', exchange: 'KOSDAQ' },
  { symbol: '403870', name: 'HPSP', exchange: 'KOSDAQ' },
  { symbol: '101490', name: 'ISC', exchange: 'KOSDAQ' },
  { symbol: '036930', name: '주성엔지니어링', exchange: 'KOSDAQ' },
  { symbol: '102940', name: '코오롱생명과학', exchange: 'KOSDAQ' },
  { symbol: '036200', name: '유니셈', exchange: 'KOSDAQ' },

  { symbol: '005290', name: '동진쎄미켐', exchange: 'KOSDAQ' },
  { symbol: '089790', name: '제이티', exchange: 'KOSDAQ' },
  { symbol: '039440', name: '에스티아이', exchange: 'KOSDAQ' },
  { symbol: '357340', name: '클리오', exchange: 'KOSDAQ' },
  { symbol: '214320', name: '이노션', exchange: 'KOSPI' },
  { symbol: '030000', name: '제일기획', exchange: 'KOSPI' },
  { symbol: '090430', name: '아모레퍼시픽', exchange: 'KOSPI' },
  { symbol: '161890', name: '한국콜마', exchange: 'KOSPI' },
  { symbol: '237690', name: '에스티팜', exchange: 'KOSDAQ' },
  { symbol: '950130', name: '엑세스바이오', exchange: 'KOSDAQ' },

  { symbol: '214450', name: '파마리서치', exchange: 'KOSDAQ' },
  { symbol: '068760', name: '셀트리온제약', exchange: 'KOSDAQ' },
  { symbol: '064350', name: '현대로템', exchange: 'KOSPI' },
  { symbol: '005940', name: 'NH투자증권', exchange: 'KOSPI' },
  { symbol: '016360', name: '삼성증권', exchange: 'KOSPI' },
  { symbol: '006800', name: '미래에셋증권', exchange: 'KOSPI' },
  { symbol: '039490', name: '키움증권', exchange: 'KOSPI' },
  { symbol: '071050', name: '한국금융지주', exchange: 'KOSPI' },
  { symbol: '323410', name: '카카오뱅크', exchange: 'KOSPI' },

  { symbol: '352480', name: '씨앤씨인터내셔널', exchange: 'KOSDAQ' },
  { symbol: '192080', name: '더블유게임즈', exchange: 'KOSPI' },
  { symbol: '365340', name: '성일하이텍', exchange: 'KOSDAQ' },
  { symbol: '900140', name: '엘브이엠씨홀딩스', exchange: 'KOSPI' },
  { symbol: '042000', name: '카페24', exchange: 'KOSDAQ' },
  { symbol: '214270', name: 'FSN', exchange: 'KOSDAQ' },
  { symbol: '377480', name: '마음AI', exchange: 'KOSDAQ' },
  { symbol: '347860', name: '알체라', exchange: 'KOSDAQ' },
  { symbol: '348210', name: '넥스틴', exchange: 'KOSDAQ' },

  { symbol: '195940', name: 'HK이노엔', exchange: 'KOSDAQ' },
  { symbol: '058820', name: 'CMG제약', exchange: 'KOSDAQ' },
  { symbol: '214370', name: '케어젠', exchange: 'KOSDAQ' },
  { symbol: '141080', name: '리가켐바이오', exchange: 'KOSDAQ' },
  { symbol: '237880', name: '클리노믹스', exchange: 'KOSDAQ' },
  { symbol: '950160', name: '코오롱티슈진', exchange: 'KOSDAQ' },
  { symbol: '214680', name: '디알텍', exchange: 'KOSDAQ' },
  { symbol: '145720', name: '덴티움', exchange: 'KOSPI' },
  { symbol: '060150', name: '인선이엔티', exchange: 'KOSDAQ' },
  { symbol: '900290', name: 'GRT', exchange: 'KOSDAQ' },

  { symbol: '091700', name: '파트론', exchange: 'KOSDAQ' },
  { symbol: '091440', name: '텔레칩스', exchange: 'KOSDAQ' },
  { symbol: '108320', name: 'LX세미콘', exchange: 'KOSPI' },
  { symbol: '137400', name: '피엔티', exchange: 'KOSDAQ' },
  { symbol: '214980', name: 'SK디앤디', exchange: 'KOSPI' },
  { symbol: '298040', name: '효성중공업', exchange: 'KOSPI' },
  { symbol: '000150', name: '두산', exchange: 'KOSPI' },
  { symbol: '004020', name: '현대제철', exchange: 'KOSPI' },
  { symbol: '005490', name: 'POSCO홀딩스', exchange: 'KOSPI' },

  { symbol: '009830', name: '한화솔루션', exchange: 'KOSPI' },
  { symbol: '011790', name: 'SKC', exchange: 'KOSPI' },
  { symbol: '282330', name: 'BGF리테일', exchange: 'KOSPI' },
  { symbol: '139480', name: '이마트', exchange: 'KOSPI' },
  { symbol: '023530', name: '롯데쇼핑', exchange: 'KOSPI' },
  { symbol: '139130', name: 'DGB금융지주', exchange: 'KOSPI' },
  { symbol: '138930', name: 'BNK금융지주', exchange: 'KOSPI' },
  { symbol: '175330', name: 'JB금융지주', exchange: 'KOSPI' },

  { symbol: '005830', name: 'DB손해보험', exchange: 'KOSPI' },
  { symbol: '001450', name: '현대해상', exchange: 'KOSPI' },
  { symbol: '282690', name: '동아타이어', exchange: 'KOSPI' },
  { symbol: '003240', name: '태광산업', exchange: 'KOSPI' },
  { symbol: '004370', name: '농심', exchange: 'KOSPI' },
  { symbol: '005300', name: '롯데칠성', exchange: 'KOSPI' },
  { symbol: '051900', name: 'LG생활건강', exchange: 'KOSPI' },
  { symbol: '009240', name: '한샘', exchange: 'KOSPI' },
  { symbol: '000880', name: '한화', exchange: 'KOSPI' },
  { symbol: '004990', name: '롯데지주', exchange: 'KOSPI' },

  { symbol: '298050', name: '효성첨단소재', exchange: 'KOSPI' },
  { symbol: '014680', name: '한솔케미칼', exchange: 'KOSPI' },
  { symbol: '336570', name: '원텍', exchange: 'KOSDAQ' },
  { symbol: '950170', name: 'JTC', exchange: 'KOSDAQ' },
  { symbol: '290650', name: '엘앤씨바이오', exchange: 'KOSDAQ' },
  { symbol: '041960', name: '코미팜', exchange: 'KOSDAQ' },
  { symbol: '067310', name: '하나마이크론', exchange: 'KOSDAQ' },
  { symbol: '089030', name: '테크윙', exchange: 'KOSDAQ' },

  { symbol: '039240', name: '경남스틸', exchange: 'KOSDAQ' },
  { symbol: '101360', name: '에코앤드림', exchange: 'KOSDAQ' },
  { symbol: '036810', name: '에프에스티', exchange: 'KOSDAQ' },
  { symbol: '253450', name: '스튜디오드래곤', exchange: 'KOSDAQ' },
  { symbol: '122450', name: 'KX', exchange: 'KOSDAQ' },
  { symbol: '036540', name: 'SFA반도체', exchange: 'KOSDAQ' },
  { symbol: '222080', name: '씨아이에스', exchange: 'KOSDAQ' },
  { symbol: '083650', name: '비에이치아이', exchange: 'KOSDAQ' },
  { symbol: '214420', name: '토니모리', exchange: 'KOSPI' },
  { symbol: '078930', name: 'GS', exchange: 'KOSPI' },

  { symbol: '383220', name: 'F&F', exchange: 'KOSPI' },
  { symbol: '105630', name: '한세실업', exchange: 'KOSPI' },
  { symbol: '180640', name: '한진칼', exchange: 'KOSPI' },
  { symbol: '003230', name: '삼양식품', exchange: 'KOSPI' },
  { symbol: '004170', name: '신세계', exchange: 'KOSPI' },
  { symbol: '069960', name: '현대백화점', exchange: 'KOSPI' },
  { symbol: '003090', name: '대웅', exchange: 'KOSPI' },
  { symbol: '069620', name: '대웅제약', exchange: 'KOSPI' },
  { symbol: '214390', name: '경보제약', exchange: 'KOSPI' },

  { symbol: '051600', name: '한전KPS', exchange: 'KOSPI' },
  { symbol: '051610', name: '한전산업', exchange: 'KOSPI' },
  { symbol: '130660', name: '한전기술', exchange: 'KOSPI' },
  { symbol: '103140', name: '풍산', exchange: 'KOSPI' },
  { symbol: '004270', name: '남성', exchange: 'KOSPI' },
  { symbol: '001040', name: 'CJ', exchange: 'KOSPI' },
  { symbol: '000120', name: 'CJ대한통운', exchange: 'KOSPI' },
  { symbol: '097230', name: 'HJ중공업', exchange: 'KOSPI' },
  { symbol: '005950', name: '이수화학', exchange: 'KOSPI' },
  { symbol: '004000', name: '롯데정밀화학', exchange: 'KOSPI' },

  { symbol: '014820', name: '동원시스템즈', exchange: 'KOSPI' },
  { symbol: '005070', name: '코스모신소재', exchange: 'KOSPI' },
  { symbol: '298020', name: '효성티앤씨', exchange: 'KOSPI' },
  { symbol: '004490', name: '세방전지', exchange: 'KOSPI' },
  { symbol: '000210', name: 'DL', exchange: 'KOSPI' },
  { symbol: '375500', name: 'DL이앤씨', exchange: 'KOSPI' },
  { symbol: '006360', name: 'GS건설', exchange: 'KOSPI' },
  { symbol: '028670', name: '팬오션', exchange: 'KOSPI' },
  { symbol: '005850', name: '에스엘', exchange: 'KOSPI' },
  { symbol: '010130', name: '고려아연', exchange: 'KOSPI' },

  { symbol: '000670', name: '영풍', exchange: 'KOSPI' },
  { symbol: '005810', name: '풍산홀딩스', exchange: 'KOSPI' },
  { symbol: '272450', name: '진에어', exchange: 'KOSPI' },
  { symbol: '020560', name: '아시아나항공', exchange: 'KOSPI' },
  { symbol: '089590', name: '제주항공', exchange: 'KOSPI' },
  { symbol: '020150', name: '일진머티리얼즈', exchange: 'KOSPI' },
  { symbol: '271940', name: '일진하이솔루스', exchange: 'KOSPI' },
  { symbol: '004800', name: '효성', exchange: 'KOSPI' },
  { symbol: '298000', name: '효성화학', exchange: 'KOSPI' },
  { symbol: '004910', name: '조광페인트', exchange: 'KOSPI' },

  { symbol: '006650', name: '대한유화', exchange: 'KOSPI' },
  { symbol: '014830', name: '유니드', exchange: 'KOSPI' },
  { symbol: '005420', name: '코스모화학', exchange: 'KOSPI' },
  { symbol: '001230', name: '동국제강', exchange: 'KOSPI' },
  { symbol: '460860', name: '동국씨엠', exchange: 'KOSPI' },
  { symbol: '460850', name: '동국제강홀딩스', exchange: 'KOSPI' },
  { symbol: '005440', name: '현대지에프홀딩스', exchange: 'KOSPI' },
  { symbol: '000500', name: '가온전선', exchange: 'KOSPI' },
  { symbol: '001820', name: '삼화콘덴서', exchange: 'KOSPI' },
  { symbol: '009470', name: '삼화전기', exchange: 'KOSPI' },

  { symbol: '009310', name: '참엔지니어링', exchange: 'KOSPI' },
  { symbol: '007660', name: '이수페타시스', exchange: 'KOSPI' },
  { symbol: '001060', name: 'JW중외제약', exchange: 'KOSPI' },
  { symbol: '000250', name: '삼천당제약', exchange: 'KOSDAQ' },
  { symbol: '084110', name: '휴온스글로벌', exchange: 'KOSDAQ' },
  { symbol: '243070', name: '휴온스', exchange: 'KOSDAQ' },
  { symbol: '084850', name: '아이티엠반도체', exchange: 'KOSDAQ' },
  { symbol: '095340', name: 'ISC', exchange: 'KOSDAQ' },
  { symbol: '064760', name: '티씨케이', exchange: 'KOSDAQ' },

  { symbol: '078600', name: '대주전자재료', exchange: 'KOSDAQ' },
  { symbol: '048260', name: '오스템임플란트', exchange: 'KOSDAQ' },
  { symbol: '085660', name: '차바이오텍', exchange: 'KOSDAQ' },
  { symbol: '064550', name: '바이오니아', exchange: 'KOSDAQ' },
  { symbol: '078130', name: '국일제지', exchange: 'KOSDAQ' },
  { symbol: '046890', name: '서울반도체', exchange: 'KOSDAQ' },
  { symbol: '082270', name: '젬백스', exchange: 'KOSDAQ' },
  { symbol: '214610', name: '미코바이오메드', exchange: 'KOSDAQ' },
  { symbol: '041920', name: '메디아나', exchange: 'KOSDAQ' },

  { symbol: '039200', name: '오스코텍', exchange: 'KOSDAQ' },
  { symbol: '060720', name: 'KH바텍', exchange: 'KOSDAQ' },
  { symbol: '131970', name: '두산테스나', exchange: 'KOSDAQ' },
  { symbol: '183300', name: '코미코', exchange: 'KOSDAQ' },
  { symbol: '240600', name: '유진테크', exchange: 'KOSDAQ' },
  { symbol: '319660', name: '피에스케이', exchange: 'KOSDAQ' },
  { symbol: '161580', name: '필옵틱스', exchange: 'KOSDAQ' },
  { symbol: '074600', name: '원익QnC', exchange: 'KOSDAQ' },
  { symbol: '178320', name: '서진시스템', exchange: 'KOSDAQ' },

  { symbol: '131290', name: '티에스이', exchange: 'KOSDAQ' },
  { symbol: '089970', name: '에이피티씨', exchange: 'KOSDAQ' },
  { symbol: '253590', name: '네오셈', exchange: 'KOSDAQ' },
  { symbol: '140860', name: '파크시스템스', exchange: 'KOSDAQ' },
  { symbol: '095610', name: '테스', exchange: 'KOSDAQ' },
  { symbol: '039030', name: '이오테크닉스', exchange: 'KOSDAQ' },
  { symbol: '036830', name: '솔브레인홀딩스', exchange: 'KOSDAQ' },
  { symbol: '222800', name: '심텍', exchange: 'KOSDAQ' },
  { symbol: '089140', name: '넥스턴바이오', exchange: 'KOSDAQ' },

  { symbol: '299900', name: '위지윅스튜디오', exchange: 'KOSDAQ' },
  { symbol: '041190', name: '우리기술투자', exchange: 'KOSDAQ' },
  { symbol: '094360', name: '칩스앤미디어', exchange: 'KOSDAQ' },
  { symbol: '293780', name: '압타바이오', exchange: 'KOSDAQ' },
  { symbol: '950190', name: '미투온', exchange: 'KOSDAQ' },
  { symbol: '065350', name: '신성델타테크', exchange: 'KOSDAQ' },
  { symbol: '900300', name: '오가닉티코스메틱', exchange: 'KOSDAQ' },
  { symbol: '290670', name: '대보마그네틱', exchange: 'KOSDAQ' },
  { symbol: '101730', name: '위메이드맥스', exchange: 'KOSDAQ' },
  { symbol: '263720', name: '디앤씨미디어', exchange: 'KOSDAQ' },

  { symbol: '099320', name: '쎄트렉아이', exchange: 'KOSDAQ' },
  { symbol: '049070', name: '인탑스', exchange: 'KOSDAQ' },
  { symbol: '053610', name: '프로텍', exchange: 'KOSDAQ' },
  { symbol: '108860', name: '셀바스AI', exchange: 'KOSDAQ' },
  { symbol: '377030', name: '맥스트', exchange: 'KOSDAQ' },
  { symbol: '256840', name: '한국비엔씨', exchange: 'KOSDAQ' },
  { symbol: '065450', name: '빅텍', exchange: 'KOSDAQ' },
  { symbol: '041140', name: '넥슨게임즈', exchange: 'KOSDAQ' },
  { symbol: '053030', name: '바텍', exchange: 'KOSDAQ' },
  { symbol: '078340', name: '컴투스', exchange: 'KOSDAQ' },

  { symbol: '263860', name: '지니언스', exchange: 'KOSDAQ' },
  { symbol: '189300', name: '인텔리안테크', exchange: 'KOSDAQ' },
  { symbol: '033640', name: '네패스', exchange: 'KOSDAQ' },
  { symbol: '046210', name: '파나진', exchange: 'KOSDAQ' },
  { symbol: '214310', name: '에스엘에스바이오', exchange: 'KOSDAQ' },
  { symbol: '078020', name: '이베스트투자증권', exchange: 'KOSDAQ' },
  { symbol: '036170', name: '클라우드에어', exchange: 'KOSDAQ' },
  { symbol: '052400', name: '코나아이', exchange: 'KOSDAQ' },
  { symbol: '290090', name: '트윔', exchange: 'KOSDAQ' },
  { symbol: '238090', name: '앤디포스', exchange: 'KOSDAQ' },

  { symbol: '010950', name: 'S-Oil', exchange: 'KOSPI' },
  { symbol: '267290', name: '경동도시가스', exchange: 'KOSDAQ' },
  { symbol: '001740', name: 'SK네트웍스', exchange: 'KOSPI' },
  { symbol: '006120', name: 'SK디스커버리', exchange: 'KOSPI' },
  { symbol: '001120', name: 'LX인터내셔널', exchange: 'KOSPI' },
  { symbol: '003620', name: 'KG모빌리티', exchange: 'KOSPI' },
  { symbol: '161390', name: '한국타이어앤테크놀로지', exchange: 'KOSPI' },
  { symbol: '073240', name: '금호타이어', exchange: 'KOSPI' },
  { symbol: '192400', name: '쿠쿠홀딩스', exchange: 'KOSPI' },

  { symbol: '284740', name: '쿠쿠홈시스', exchange: 'KOSPI' },
  { symbol: '018880', name: '한온시스템', exchange: 'KOSPI' },
  { symbol: '047040', name: '대우건설', exchange: 'KOSPI' },
  { symbol: '37550K', name: 'DL이앤씨우', exchange: 'KOSPI' },
  { symbol: '001800', name: '오리온홀딩스', exchange: 'KOSPI' },
  { symbol: '000070', name: '삼양홀딩스', exchange: 'KOSPI' },
  { symbol: '000640', name: '동아쏘시오홀딩스', exchange: 'KOSPI' },
  { symbol: '003850', name: '보령', exchange: 'KOSPI' },

  { symbol: '000520', name: '삼일제약', exchange: 'KOSPI' },
  { symbol: '271980', name: '제일약품', exchange: 'KOSPI' },
  { symbol: '185750', name: '종근당', exchange: 'KOSPI' },
  { symbol: '001630', name: '종근당홀딩스', exchange: 'KOSPI' },
  { symbol: '185490', name: '아이진', exchange: 'KOSDAQ' },
  { symbol: '950210', name: '프레스티지바이오파마', exchange: 'KOSPI' },
  { symbol: '334970', name: '프레스티지바이오로직스', exchange: 'KOSDAQ' },
  { symbol: '950220', name: '네오이뮨텍', exchange: 'KOSDAQ' },
  { symbol: '950140', name: '잉글우드랩', exchange: 'KOSDAQ' },
  { symbol: '064090', name: '인크로스', exchange: 'KOSDAQ' },

  { symbol: '214180', name: '케이엔제이', exchange: 'KOSDAQ' },
  { symbol: '036710', name: '심텍홀딩스', exchange: 'KOSDAQ' },
  { symbol: '064290', name: '인텍플러스', exchange: 'KOSDAQ' },
  { symbol: '078150', name: 'HB테크놀러지', exchange: 'KOSDAQ' },
  { symbol: '265520', name: 'AP시스템', exchange: 'KOSDAQ' },
  { symbol: '042110', name: '에스씨엠생명과학', exchange: 'KOSDAQ' },
  { symbol: '290510', name: '코리아센터', exchange: 'KOSDAQ' },
  { symbol: '053580', name: '웹케시', exchange: 'KOSDAQ' },
  { symbol: '041460', name: '한국전자인증', exchange: 'KOSDAQ' },
  { symbol: '377450', name: '리파인', exchange: 'KOSDAQ' },

  { symbol: '041020', name: '폴라리스오피스', exchange: 'KOSDAQ' },
  { symbol: '402340', name: 'SK스퀘어', exchange: 'KOSPI' },
  { symbol: '377740', name: '바이오노트', exchange: 'KOSPI' },
  { symbol: '058610', name: '에스피지', exchange: 'KOSDAQ' },
  { symbol: '090360', name: '로보스타', exchange: 'KOSDAQ' },
  { symbol: '454910', name: '두산로보틱스', exchange: 'KOSPI' },
  { symbol: '277810', name: '레인보우로보틱스', exchange: 'KOSDAQ' },
  { symbol: '108490', name: '로보티즈', exchange: 'KOSDAQ' },
  { symbol: '090710', name: '휴림로봇', exchange: 'KOSDAQ' },
  { symbol: '340930', name: '유일로보틱스', exchange: 'KOSDAQ' },

  { symbol: '256940', name: '케이피에스', exchange: 'KOSDAQ' },
  { symbol: '099440', name: '스맥', exchange: 'KOSDAQ' },
  { symbol: '056080', name: '유진로봇', exchange: 'KOSDAQ' },
  { symbol: '173130', name: '오픈엣지테크놀로지', exchange: 'KOSDAQ' },
  { symbol: '402030', name: '코난테크놀로지', exchange: 'KOSDAQ' },
  { symbol: '304100', name: '솔트룩스', exchange: 'KOSDAQ' },
  { symbol: '417970', name: '모아데이타', exchange: 'KOSDAQ' },
  { symbol: '418620', name: '메타보라', exchange: 'KOSDAQ' },
  { symbol: '347770', name: '핌스', exchange: 'KOSDAQ' },
  { symbol: '389500', name: '에스비비테크', exchange: 'KOSDAQ' },

  { symbol: '417200', name: 'LS머트리얼즈', exchange: 'KOSDAQ' },
  { symbol: '092200', name: '디아이씨', exchange: 'KOSPI' },
  { symbol: '089860', name: '롯데렌탈', exchange: 'KOSPI' },
  { symbol: '032350', name: '롯데관광개발', exchange: 'KOSPI' },
  { symbol: '251370', name: '와이엠티', exchange: 'KOSDAQ' },
  { symbol: '091580', name: '상신이디피', exchange: 'KOSDAQ' },
  { symbol: '361610', name: 'SK아이이테크놀로지', exchange: 'KOSPI' },
  { symbol: '357550', name: '석경에이티', exchange: 'KOSDAQ' },
  { symbol: '200670', name: '휴메딕스', exchange: 'KOSDAQ' },

  { symbol: '200130', name: '콜마비앤에이치', exchange: 'KOSDAQ' },
  { symbol: '067630', name: 'HLB생명과학', exchange: 'KOSDAQ' },
  { symbol: '028300', name: 'HLB', exchange: 'KOSDAQ' },
  { symbol: '115450', name: 'HLB테라퓨틱스', exchange: 'KOSDAQ' },
  { symbol: '067080', name: '대화제약', exchange: 'KOSDAQ' },
  { symbol: '290550', name: '디케이티', exchange: 'KOSDAQ' },
  { symbol: '222110', name: '팬스타엔터프라이즈', exchange: 'KOSDAQ' },

  { symbol: '290380', name: '대유에이피', exchange: 'KOSDAQ' },
  { symbol: '033170', name: '시그네틱스', exchange: 'KOSDAQ' },
  { symbol: '101160', name: '월덱스', exchange: 'KOSDAQ' },
  { symbol: '220260', name: '켐트로스', exchange: 'KOSDAQ' },
  { symbol: '365270', name: '큐라클', exchange: 'KOSDAQ' },
  { symbol: '086450', name: '동국제약', exchange: 'KOSDAQ' },

  { symbol: '041830', name: '인바디', exchange: 'KOSDAQ' },
  { symbol: '196300', name: '애니젠', exchange: 'KOSDAQ' },
  { symbol: '095700', name: '제넥신', exchange: 'KOSDAQ' },
  { symbol: '084990', name: '헬릭스미스', exchange: 'KOSDAQ' },
  { symbol: '246720', name: '아스타', exchange: 'KOSDAQ' },
  { symbol: '187660', name: '현대ADM', exchange: 'KOSDAQ' },
  { symbol: '214260', name: '라파스', exchange: 'KOSDAQ' },
  { symbol: '290690', name: '소룩스', exchange: 'KOSDAQ' },
  { symbol: '101390', name: '아이엠', exchange: 'KOSDAQ' },

  { symbol: '123570', name: '이엠넷', exchange: 'KOSDAQ' },
  { symbol: '215000', name: '골프존', exchange: 'KOSDAQ' },
  { symbol: '299030', name: '하나기술', exchange: 'KOSDAQ' },
  { symbol: '131370', name: '알서포트', exchange: 'KOSDAQ' },
  { symbol: '352770', name: '클리노믹스', exchange: 'KOSDAQ' },
  { symbol: '036620', name: '감성코퍼레이션', exchange: 'KOSDAQ' },
  { symbol: '089980', name: '상아프론테크', exchange: 'KOSDAQ' },
  { symbol: '417840', name: '저스템', exchange: 'KOSDAQ' },
  { symbol: '065660', name: '안트로젠', exchange: 'KOSDAQ' },

  { symbol: '347890', name: '엠투아이', exchange: 'KOSDAQ' },
  { symbol: '039980', name: '폴라리스AI', exchange: 'KOSDAQ' },
  { symbol: '900270', name: '헝셩그룹', exchange: 'KOSDAQ' },
  { symbol: '263050', name: '유틸렉스', exchange: 'KOSDAQ' },
  { symbol: '065370', name: '위세아이텍', exchange: 'KOSDAQ' },
  { symbol: '321820', name: '와이더플래닛', exchange: 'KOSDAQ' },
  { symbol: '047560', name: '이스트소프트', exchange: 'KOSDAQ' },
  { symbol: '053290', name: 'NE능률', exchange: 'KOSDAQ' },
  { symbol: '053800', name: '안랩', exchange: 'KOSDAQ' },

  { symbol: '067000', name: '조이시티', exchange: 'KOSDAQ' },
  { symbol: '078000', name: '텔코웨어', exchange: 'KOSDAQ' },
  { symbol: '036800', name: '나이스정보통신', exchange: 'KOSDAQ' },
  { symbol: '950110', name: 'SBI핀테크솔루션즈', exchange: 'KOSDAQ' },
  { symbol: '377300', name: '카카오페이', exchange: 'KOSPI' },
  { symbol: '094940', name: '푸른기술', exchange: 'KOSDAQ' },
  { symbol: '060250', name: 'NHN KCP', exchange: 'KOSDAQ' },
  { symbol: '046440', name: 'KG모빌리언스', exchange: 'KOSDAQ' },
  { symbol: '052220', name: 'iMBC', exchange: 'KOSDAQ' },
  { symbol: '058850', name: 'KTcs', exchange: 'KOSPI' },

  { symbol: '030520', name: '한글과컴퓨터', exchange: 'KOSDAQ' },
  { symbol: '093320', name: '케이아이엔엑스', exchange: 'KOSDAQ' },
  { symbol: '036030', name: '케이티알파', exchange: 'KOSDAQ' },
  { symbol: '035460', name: '기산텔레콤', exchange: 'KOSDAQ' },
  { symbol: '060570', name: '드림어스컴퍼니', exchange: 'KOSDAQ' },
  { symbol: '123420', name: '위메이드플레이', exchange: 'KOSDAQ' },
  { symbol: '950200', name: '소마젠', exchange: 'KOSDAQ' },
  { symbol: '900250', name: '크리스탈신소재', exchange: 'KOSDAQ' },
];

export async function GET(request) {
  const { searchParams } = new URL(request.url);
  const query = searchParams.get('q')?.trim().toLowerCase();

  if (!query) return Response.json({ results: [] });

  // 1. 인기 종목에서 먼저 검색
  const localResults = POPULAR_STOCKS.filter(
    (stock) =>
      stock.name.toLowerCase().includes(query) ||
      stock.symbol.includes(query)
  );

  // 2. KRX API로 추가 검색
  try {
    const res = await fetch(
      'https://kind.krx.co.kr/common/searchcorpname.do?method=searchCorpNameJson&searchCodeType=&searchCorpName=' +
      encodeURIComponent(query),
      {
        headers: {
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
          'Referer': 'https://kind.krx.co.kr',
          'Accept': 'application/json',
        },
      }
    );

    const data = await res.json();
    const list = Array.isArray(data) ? data : (data.result || []);
    const krxResults = list.map((item) => ({
      symbol: item.repisusrtcd?.replace('A', '') || item.kiscomcd,
      name: item.repisusrtkornm || item.comabbrv,
      exchange: item.spotisutrdmkttpcd === '2' ? 'KOSDAQ' : 'KOSPI',
    })).filter((item) => item.symbol && item.name);

    // 3. 로컬 + KRX 합치되 중복 제거
    const combined = [...localResults];
    krxResults.forEach((krx) => {
      if (!combined.find((l) => l.symbol === krx.symbol)) {
        combined.push(krx);
      }
    });

    return Response.json({ results: combined.slice(0, 8) });
  } catch {
    return Response.json({ results: localResults.slice(0, 8) });
  }
}